// AI Review Insights App — LLM summary + reviews with resolve

const ReviewInsightsApp = ({ go }) => {
  const [reviews, setReviews] = React.useState(REVIEWS);
  const [filter, setFilter] = React.useState('open');
  const [expandedTheme, setExpandedTheme] = React.useState(null);

  const visible = reviews.filter(r => filter === 'all' ? true : (filter === 'open' ? !r.resolved : r.resolved));
  const openCount = reviews.filter(r => !r.resolved).length;

  const resolve = (id) => {
    setReviews(rs => rs.map(r => r.id === id ? { ...r, resolved: true } : r));
  };

  return (
    <PageShell>
      <Breadcrumbs items={[
        { label: 'Data Apps' },
        { label: 'AI Review Insights' },
      ]} />
      <PageTitle
        title="AI Review Insights"
        subtitle="LLM-summarised customer complaints with urgency scoring and resolve workflow."
        action={<Button variant="ghost" icon="refresh">Regenerate summary</Button>}
      />

      {/* Summary panel */}
      <div style={{
        background: 'linear-gradient(135deg, oklch(0.98 0.03 265) 0%, oklch(0.97 0.03 305) 100%)',
        border: '1px solid oklch(0.9 0.04 265)',
        borderRadius: 14, padding: 20, marginBottom: 22,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 14 }}>
          <div style={{
            width: 30, height: 30, borderRadius: 8,
            background: 'linear-gradient(135deg, oklch(0.55 0.18 265), oklch(0.6 0.18 305))',
            display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <Icon name="sparkles" size={15} style={{ color: '#fff' }} />
          </div>
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 13.5, fontWeight: 600 }}>Weekly complaint summary</div>
            <div style={{ fontSize: 11.5, color: 'var(--fg-muted)' }}>Generated by Claude · {REVIEW_SUMMARY.generated}</div>
          </div>
          <div style={{ display: 'flex', gap: 14 }}>
            <div>
              <div style={{ fontSize: 11, color: 'var(--fg-muted)' }}>Urgent</div>
              <div style={{ fontSize: 20, fontWeight: 600, color: 'var(--danger)' }}>{REVIEW_SUMMARY.totalUrgent}</div>
            </div>
            <div>
              <div style={{ fontSize: 11, color: 'var(--fg-muted)' }}>7-day total</div>
              <div style={{ fontSize: 20, fontWeight: 600 }}>{REVIEW_SUMMARY.total7d}</div>
            </div>
          </div>
        </div>

        {/* Themes */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 10, marginBottom: 14 }}>
          {REVIEW_SUMMARY.topThemes.map(t => {
            const toneColor = t.tone === 'danger' ? 'var(--danger)' : t.tone === 'warn' ? 'var(--warn)' : 'var(--fg-muted)';
            return (
              <button key={t.label} onClick={() => setExpandedTheme(expandedTheme === t.label ? null : t.label)} style={{
                background: 'var(--bg-elev)', border: '1px solid var(--border)',
                borderRadius: 10, padding: 12, textAlign: 'left',
                transition: 'all .15s ease',
              }}
                onMouseEnter={e => { e.currentTarget.style.borderColor = 'var(--border-strong)'; e.currentTarget.style.boxShadow = 'var(--shadow-xs)'; }}
                onMouseLeave={e => { e.currentTarget.style.borderColor = 'var(--border)'; e.currentTarget.style.boxShadow = 'none'; }}
              >
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 }}>
                  <div style={{ fontSize: 12.5, fontWeight: 500 }}>{t.label}</div>
                  <div style={{ fontSize: 16, fontWeight: 600, color: toneColor }}>{t.count}</div>
                </div>
                <div style={{ height: 4, background: 'var(--bg-muted)', borderRadius: 2, overflow: 'hidden' }}>
                  <div style={{ width: `${t.share * 100}%`, height: '100%', background: toneColor }} />
                </div>
                <div style={{ fontSize: 10.5, color: 'var(--fg-muted)', marginTop: 6 }}>{Math.round(t.share * 100)}% of urgent · {t.delta}</div>
              </button>
            );
          })}
        </div>

        {/* Narrative */}
        <div style={{
          background: 'var(--bg-elev)', border: '1px solid var(--border)',
          borderRadius: 10, padding: 14, fontSize: 13, lineHeight: 1.6, color: 'var(--fg)',
        }}>
          <div style={{ fontSize: 10.5, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '.07em', color: 'var(--fg-soft)', marginBottom: 6 }}>Narrative</div>
          {REVIEW_SUMMARY.narrative}
        </div>
      </div>

      {/* Reviews list */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 14 }}>
        <h2 style={{ margin: 0, fontSize: 16, fontWeight: 600, letterSpacing: '-.01em' }}>Urgent reviews</h2>
        <div style={{ display: 'flex', gap: 4, background: 'var(--bg-muted)', padding: 3, borderRadius: 8 }}>
          {[
            { k: 'open',     label: `Open (${openCount})` },
            { k: 'resolved', label: `Resolved (${reviews.length - openCount})` },
            { k: 'all',      label: 'All' },
          ].map(t => (
            <button key={t.k} onClick={() => setFilter(t.k)} style={{
              padding: '5px 11px', borderRadius: 6, fontSize: 12, fontWeight: 500,
              background: filter === t.k ? 'var(--bg-elev)' : 'transparent',
              boxShadow: filter === t.k ? 'var(--shadow-xs)' : 'none',
              color: filter === t.k ? 'var(--fg)' : 'var(--fg-muted)',
            }}>{t.label}</button>
          ))}
        </div>
        <div style={{ flex: 1 }} />
        <Button variant="ghost" size="sm" icon="external">Operational Board</Button>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        {visible.map((r, i) => <ReviewCard key={r.id} review={r} index={i + 1} onResolve={() => resolve(r.id)} />)}
        {visible.length === 0 && <Empty icon="check" title="All clear" subtitle="No reviews match this filter." />}
      </div>
    </PageShell>
  );
};

const ReviewCard = ({ review, index, onResolve }) => {
  const urgencyColor =
    review.urgency >= 4 ? 'var(--danger)' :
    review.urgency >= 3 ? 'var(--warn)' : 'var(--fg-muted)';

  return (
    <Card style={{ padding: 16, opacity: review.resolved ? 0.65 : 1 }}>
      {/* Meta line */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap', fontSize: 12, color: 'var(--fg-muted)' }}>
        <div style={{
          width: 22, height: 22, borderRadius: '50%',
          background: 'linear-gradient(135deg, oklch(0.7 0.1 25), oklch(0.65 0.15 35))',
          display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
        }}>
          <Icon name="alert" size={11} style={{ color: '#fff' }} />
        </div>
        <span style={{ fontWeight: 600, color: 'var(--fg)' }}>#{index}</span>
        <span>·</span>
        <span>Order {review.order}</span>
        <span>·</span>
        <span>{review.brand}</span>
        <span>·</span>
        <span style={{ fontWeight: 500 }}>{review.country}</span>
        <span style={{ marginLeft: 'auto' }} />
        <div style={{ display: 'flex', gap: 1 }}>
          {[1,2,3,4,5].map(s => (
            <Icon key={s} name={s <= review.rating ? 'starFill' : 'star'} size={12} style={{ color: s <= review.rating ? 'var(--warn)' : 'var(--border-strong)' }} />
          ))}
        </div>
        <span>·</span>
        <span>Urgency: <strong style={{ color: urgencyColor }}>{review.urgency}</strong></span>
        <span>·</span>
        <span>{review.time}</span>
      </div>

      {/* Category tag */}
      <div style={{ marginTop: 10 }}>
        <span style={{
          display: 'inline-block',
          padding: '3px 10px', borderRadius: 4,
          fontSize: 11.5, fontWeight: 500,
          background: 'oklch(0.96 0.04 25)', color: 'var(--danger)',
          border: '1px solid oklch(0.9 0.05 25)',
        }}>{review.category}</span>
        {review.resolved && (
          <span style={{
            display: 'inline-block', marginLeft: 8,
            padding: '3px 10px', borderRadius: 4,
            fontSize: 11.5, fontWeight: 500,
            background: 'var(--success-soft)', color: 'var(--success)',
          }}>✓ Resolved</span>
        )}
      </div>

      {/* Text */}
      <div style={{ marginTop: 10, fontSize: 13, lineHeight: 1.6, color: 'var(--fg)', whiteSpace: 'pre-wrap' }}>
        {review.text}
      </div>

      {/* Actions */}
      <div style={{ marginTop: 14, display: 'flex', gap: 8 }}>
        <button style={pillBtn}>Review</button>
        <button style={pillBtn}>Customer</button>
        <button style={pillBtn}>Order</button>
        {!review.resolved && (
          <button onClick={onResolve} style={{
            ...pillBtn, background: 'var(--success)', color: '#fff', border: '1px solid var(--success)',
          }}>Resolve</button>
        )}
      </div>
    </Card>
  );
};

const pillBtn = {
  padding: '6px 14px', borderRadius: 6, fontSize: 12.5, fontWeight: 500,
  background: 'var(--bg-elev)', color: 'var(--fg)',
  border: '1px solid var(--border)',
  transition: 'background .15s ease',
};

Object.assign(window, { ReviewInsightsApp });
